### PR TITLE
add brief example of configuriung a plugin

### PR DESCRIPTION
**Pull request by joelowrance**
For issue #5

### CODE REVIEW

**Comment by joelowrance** [comment]
My fault.  I will put this in the docs and do a PR on that repo.

**Comment by Alexander-Taran** [comment]
Thanks.. I actually thought of committing in your name (-:

**Comment by Alexander-Taran** [comment]
I thought maybe we could fork au repos to here.. but then again it would be some additional work to merge upstream

**Comment by joelowrance** [comment]
Added PR to correct repo, closing this.

**Pull request closed without merging**
