### PR TITLE
Create how-to-enable-gzip-compression.md

### PR DESCRIPTION
**Pull request by gama410**
A recipe for adding gzip compression to the aurelia-cli run task as discussed [here](https://github.com/aurelia/cli/issues/871#issuecomment-383745631)

### CODE REVIEW

**Comment by huochunpeng** [comment]
To be frank, I did not see much value of gzip compression for dev setup, as the bandwidth is unlikely an issue in dev mode.

As you stated in original cli issue, we don’t need compression in build either. Because in production, compression is handled at different layer (nginx for instance).

**Comment by maroy1986** [comment]
I do agree with @huochunpeng, I don't see a real value of having GZIP compression in a dev environment. As he said, this is handled by the web server (nginx, apache, iis) at the end and the CLI shouldn't even know about it.

**Comment by gama410** [comment]
You're right, there is no real need for it in dev, although I needed it for test purpose on my setup while trying to find an acceptable bundle organization...

**Comment by maroy1986** [comment]
I see now, make sense in that case. Anyway, there's never enough documentation to cover what everybody wants to do :)

**Pull request merged**
