### PR TITLE
feat: new guide: How to simplify your import paths in Typescript

### PR DESCRIPTION
**Pull request by mttmccb**
Tried to keep it simple, I don't understand the CLI part.

Also not sure if it's possible to do something similar with ES6/ES2017, maybe using babel?

### CODE REVIEW

**Comment by huochunpeng** [comment]
@Alexander-Taran pls grant all our fellow members permission to commit, if you have not.
Welcome aboard @mttmccb !

**Comment by Alexander-Taran** [comment]
@huochunpeng I did.

**Comment by huochunpeng** [comment]
Thx. Recommend everyone just commit doc directly. Doc is just doc after all, would not crash.

**Comment by mttmccb** [comment]
I did the PR before I had access :)
Wanted to make sure my contribution was decent first

**Comment by huochunpeng** [comment]
No worry :-)

**Comment by Alexander-Taran** [comment]
so sweet (-:

**Pull request merged**
